model_list:
  # Direct access models (confirmed working)
  - model_name: llama-3-8b
    litellm_params:
      model: bedrock/meta.llama3-8b-instruct-v1:0
      aws_region_name: us-east-1
      aws_profile_name: genai

  - model_name: llama-3-70b
    litellm_params:
      model: bedrock/meta.llama3-70b-instruct-v1:0
      aws_region_name: us-east-1
      aws_profile_name: genai

  # Cross-region inference models (confirmed working)
  - model_name: llama-3-2-3b
    litellm_params:
      model: bedrock/us.meta.llama3-2-3b-instruct-v1:0
      aws_region_name: us-east-1
      aws_profile_name: genai

  - model_name: llama-3-1-70b
    litellm_params:
      model: bedrock/us.meta.llama3-1-70b-instruct-v1:0
      aws_region_name: us-east-1
      aws_profile_name: genai

  - model_name: llama-3-2-90b
    litellm_params:
      model: bedrock/us.meta.llama3-2-90b-instruct-v1:0
      aws_region_name: us-east-1
      aws_profile_name: genai

  - model_name: llama-3-3-70b
    litellm_params:
      model: bedrock/us.meta.llama3-3-70b-instruct-v1:0
      aws_region_name: us-east-1
      aws_profile_name: genai

general_settings:
  master_key: bedrock-graphgen-2024
  port: 4000

general_settings:
  master_key: bedrock-graphgen-2024
  port: 4000
