from .coreference_resolution import COREFERENCE_RESOLUTION_PROMPT
from .description_rephrasing import DESCRIPTION_REPHRASING_PROMPT
from .extraction import SCHEMA_GUIDED_EXTRACTION_PROMPT
from .generation import (
    AGGREGATED_GENERATION_PROMPT,
    ATOMIC_GENERATION_PROMPT,
    COT_GENERATION_PROMPT,
    MULTI_HOP_GENERATION_PROMPT,
    VQA_GENERATION_PROMPT,
)
from .kg import KG_EXTRACTION_PROMPT, KG_SUMMARIZATION_PROMPT, MMKG_EXTRACTION_PROMPT
from .question_generation import QUESTION_GENERATION_PROMPT
from .search_judgement import SEARCH_JUDGEMENT_PROMPT
from .statement_judgement import STATEMENT_JUDGEMENT_PROMPT
